services:
  courier:
    build:
      context: .
      dockerfile: ./services/dockerfiles/courier.Dockerfile
    volumes:
      - "./requirements.txt:/requirements.txt"
      - "./potoo:/potoo/"
      - "./services/courier/:/courier"
    command:
      - /bin/sh
      - -c
      - |
        /opt/venv/bin/python -m pip install -r /requirements.txt &&
        courier run /courier/courier-potoo-service.yaml
  go_server:
    build:
      context: .
      dockerfile: ./services/dockerfiles/go-server.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./potoo/output_dir:/output_dir"
      - "./potoo/gif_dir:/gif_dir"
      - "./server/pages/:/app/pages"
