services:
  redis:
    ports:
      - "6379:6379"
    image: redis
  courier:
    build:
      context: .
      dockerfile: courier.Dockerfile
    volumes:
      - ".:/work/"
    command:
      - /bin/sh
      - -c
      - |
        /opt/venv/bin/python -m pip install -r requirements.txt &&
        courier run courier-potoo-service.yaml
  courier_redis:
    build:
      context: .
      dockerfile: courier.Dockerfile
    volumes:
      - ".:/work/"
    command:
      - /bin/sh
      - -c
      - |
        /opt/venv/bin/python -m pip install -r requirements.txt &&
        courier run potoo-redis-poller-service.yaml
  output_watcher:
    build:
      context: .
      dockerfile: courier.Dockerfile
    volumes:
      - ".:/work/"
    command:
      - /bin/sh
      - -c
      - |
        /opt/venv/bin/python -m pip install -r requirements.txt &&
        courier run potoo-output-watcher-service.yaml
  go_server:
    build:
      context: .
      dockerfile: go-server.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./gif_dir:/gif_dir"
